version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: event_management_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: event_management_nginx
    volumes:
      - ./src:/var/www
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: event_management_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: event_management_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
